Repository Gwasuwon-shot/Tutice_Client, pull requests merged in 2023-07, with the labels that each got.

#18 Feat#8 home/teacher home banner
  index.html
  src/assets/icon/attenceCheckCommonIc.svg
  src/assets/icon/upcomingClassLogoTeacherHomeIc.svg
  src/assets/index.ts
  src/atom/teacherFooterCategory.ts
  src/components/.keep
  src/components/common/AttendanceCheckButton.tsx
  src/components/common/SubjectLabel.tsx
  src/components/common/TeacherFooter.tsx
  src/components/teacherHome/AlarmBanner.tsx
  src/components/teacherHome/PreviewBanner.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/teacherHome/UpcomingClassBoard.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/components/teacherHome/WelcomeTeacher.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/components/teacherHome/banner/NoclassBanner.tsx
  src/core/teacherHome/classPreviewBannerComments.ts
  src/core/teacherHome/noClassBannerTitle.ts
  src/core/teacherHome/teacherFooter.ts
  src/core/teacherHome/teacherHome.ts
  src/core/teacherHome/welcomeTeacherComments.ts
  src/pages/Home.tsx
  src/style/globalStyle.ts
  src/style/theme.ts
  src/type/teacherHomeTodayScheduleType.ts
Labels: 지수, feat-UI, feat-function

#7 Feat#4 common/teacher footer
  index.html
  package.json
  src/assets/icon/attenceCheckCommonIc.svg
  src/assets/icon/calendarActiveTeacherFooterIc.svg
  src/assets/icon/calendarTeacherFooterIc.svg
  src/assets/icon/classManagingActiveTeacherFooterIc.svg
  src/assets/icon/classManagingTeacherFooterIc.svg
  src/assets/icon/homeActiveTeacherFooterIc.svg
  src/assets/icon/homeTeacherFooterIc.svg
  src/assets/icon/myActiveTeacherFooterIc.svg
  src/assets/icon/myTeacherFooterIc.svg
  src/assets/icon/upcomingClassLogoTeacherHomeIc.svg
  src/assets/index.ts
  src/atom/.keep
  src/atom/teacherFooterCategory.ts
  src/components/.keep
  src/components/common/AttendanceCheckButton.tsx
  src/components/common/SubjectLabel.tsx
  src/components/common/TeacherFooter.tsx
  src/components/teacherHome/AlarmBanner.tsx
  src/components/teacherHome/PreviewBanner.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/teacherHome/UpcomingClassBoard.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/components/teacherHome/WelcomeTeacher.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/components/teacherHome/banner/NoclassBanner.tsx
  src/core/.keep
  src/core/teacherHome/classPreviewBannerComments.ts
  src/core/teacherHome/noClassBannerTitle.ts
  src/core/teacherHome/teacherFooter.ts
  src/core/teacherHome/teacherHome.ts
  src/core/teacherHome/welcomeTeacherComments.ts
  src/pages/Home.tsx
  src/style/globalStyle.ts
  src/style/theme.ts
  src/type/.keep
  src/type/teacherFooterType.ts
  src/type/teacherHomeTodayScheduleType.ts
  yarn.lock
Labels: 지수, feat-UI, feat-function

#17 Feat#13 register lesson/register student and lesson name footer
  src/components/RegisterLessonPage/Footer.tsx
  src/pages/RegisterLesson.tsx
  src/style/globalStyle.ts
Labels: 희정, feat-UI

#16 Feat#6 register lesson/register student and lesson name
  src/Router.tsx
  src/assets/icon/registerLessonHeaderIc.svg
  src/assets/index.ts
  src/components/RegisterLessonPage/Footer.tsx
  src/components/RegisterLessonPage/Header.tsx
  src/components/RegisterLessonPage/LessonInput.tsx
  src/main.tsx
  src/pages/RegisterLesson.tsx
  src/style/globalStyle.ts
  src/style/theme.ts
Labels: 희정, feat-UI

#15 Feat#12 common/bottom button
  src/assets/icon/RoleCheckSignupIc.svg
  src/assets/icon/RoleNoneCheckSignupIc.svg
  src/components/common/BottomButton.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PwTos.tsx
  src/components/signup/Role.tsx
  src/components/signup/StepRenderer.tsx
  src/pages/Signup.tsx
Labels: 은빈, feat-UI, feat-function

#37 Feat#36 common/basic double modal
  src/components/common/BasicDoubleModal.tsx
  src/components/teacherHome/TeacherHome.tsx
Labels: 지수, feat-UI, feat-function, CodeReview

#35 Feat#34 common/basic single modal
  src/components/common/BasicDoubleModal.tsx
  src/components/common/BasicSingleModal.tsx
  src/components/teacherHome/TeacherHome.tsx
Labels: 지수, feat-UI, feat-function

#28 Feat#26 home/no class home
  package.json
  src/assets/icon/noClassLogoTeacherHomeIc.svg
  src/assets/index.ts
  src/atom/common/isModalOpen.ts
  src/components/common/BasicDoubleModal.tsx
  src/components/common/BasicSingleModal.tsx
  src/components/common/ToastModal.tsx
  src/components/teacherHome/NoClassHome.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/teacherHome/WelcomeTeacher.tsx
  src/hooks/.keep
  src/hooks/useModal.ts
  src/style/theme.ts
  src/utils/.keep
  src/utils/common/modal.ts
  yarn.lock
Labels: 지수, feat-UI, CodeReview

#25 Feat#24 common/round button
  src/components/common/RoundBottomButton.tsx
  vite.config.ts
Labels: 성경, feat-UI, CodeReview

#31 Feat#1 registerlesson/calendar
  package.json
  src/Router.tsx
  src/assets/icon/arrow_cal_left.svg
  src/assets/icon/arrow_cal_right.svg
  src/assets/icon/x_btn.svg
  src/assets/index.ts
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/Dayofweek.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/StickCalendar.tsx
  src/components/Calendar/YearandMonth.tsx
  src/pages/RegisterCalendar.tsx
  yarn.lock
Labels: 혜인, feat-UI, CodeReview

#43 Feat#9 signup/pw tos
  src/assets/icon/TosCheckedSignupIc.svg
  src/assets/icon/TosNoneSignupIc.svg
  src/assets/index.ts
  src/components/common/BackButton.tsx
  src/components/common/BottomButton.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PwTos.tsx
  src/components/signup/Role.tsx
  src/components/signup/SignupTitleLayout.tsx
  src/components/signup/StepRenderer.tsx
  src/components/signup/TextLabelLayout.tsx
  src/components/signup/ToS.tsx
  src/pages/Signup.tsx
Labels: 은빈, feat-UI, feat-function, CodeReview

#27 Feat#5 signup/role name email
  src/assets/icon/TosCheckedSignupIc.svg
  src/assets/icon/TosNoneSignupIc.svg
  src/assets/icon/backButtonSignupIc.svg
  src/assets/index.ts
  src/atom/signup/signup.ts
  src/components/common/BackButton.tsx
  src/components/common/BottomButton.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PwTos.tsx
  src/components/signup/Role.tsx
  src/components/signup/SignupTitleLayout.tsx
  src/components/signup/StepRenderer.tsx
  src/components/signup/TextLabelLayout.tsx
  src/components/signup/ToS.tsx
  src/pages/Signup.tsx
  src/style/theme.ts
  src/type/signupType.ts
Labels: 은빈, feat-UI, CodeReview

#51 Feat#46 common/complete attendance check
  package.json
  src/Router.tsx
  src/atom/attendanceCheck/upcomingClassData.ts
  src/components/common/AttendanceCheckModal.tsx
  src/components/common/AttendanceDoubleCheckingModal.tsx
  src/components/common/AttendanceStatusButton.tsx
  src/components/common/RoundBottomMiniButton.tsx
  src/components/common/SendAlarmCheckModal.tsx
  src/components/common/SubjectLabel.tsx
  src/components/teacherHome/PreviewBanner.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/components/teacherHome/WelcomeTeacher.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/core/checkAttendance/attendaceCheckResponse.ts
  src/core/checkAttendance/check.json
  src/core/checkAttendance/check_circle.json
  src/core/teacherHome/teacherHome.ts
  src/hooks/useModal.ts
  src/pages/CheckAttendance.tsx
  src/pages/CompleteCheckAttendance.tsx
  src/type/teacherHome/previewBannerScheduleType.ts
  yarn.lock
Labels: 지수, feat-UI, feat-function, CodeReview

#45 Feat#42 common/attendace check
  package.json
  src/Router.tsx
  src/assets/icon/absentAttendanceModalIc.svg
  src/assets/icon/attendaceAttendanceModalIc.svg
  src/assets/icon/cancelAttendanceModalIc.svg
  src/assets/index.ts
  src/atom/attendanceCheck/attendanceStatus.ts
  src/atom/attendanceCheck/upcomingClassData.ts
  src/components/common/AttendanceCheckModal.tsx
  src/components/common/AttendanceDoubleCheckingModal.tsx
  src/components/common/AttendanceStatusButton.tsx
  src/components/common/BasicDoubleModal.tsx
  src/components/common/RoundBottomMiniButton.tsx
  src/components/common/SendAlarmCheckModal.tsx
  src/components/common/SubjectLabel.tsx
  src/components/common/ToastModal.tsx
  src/components/teacherHome/PreviewBanner.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/teacherHome/UpcomingClassBoard.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/components/teacherHome/WelcomeTeacher.tsx
  src/components/teacherHome/YesClassHome.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/core/checkAttendance/attendaceCheckResponse.ts
  src/core/checkAttendance/check.json
  src/core/checkAttendance/check_circle.json
  src/core/common/attendanceStatus.ts
  src/core/teacherHome/teacherHome.ts
  src/hooks/useModal.ts
  src/pages/CheckAttendance.tsx
  src/pages/CompleteCheckAttendance.tsx
  src/type/teacherHome/previewBannerScheduleType.ts
  yarn.lock
Labels: 지수, feat-UI, feat-function, CodeReview

#53 Feat#32 parents/calendar
  src/assets/icon/calendarMoreLessonIc.svg
  src/assets/index.ts
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/Day.tsx
  src/components/Calendar/Dayofweek.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/YearandMonth.tsx
  src/core/Parents/ParentsCalendar.ts
  src/pages/ParentCalendar.tsx
  src/style/theme.ts
  src/type/calendarLessonsType.ts
Labels: 혜인, feat-UI, feat-function, CodeReview

#49 Feat#39 register lesson/regular schedule
  src/Router.tsx
  src/assets/icon/regularLessonCalenderIc.svg
  src/assets/icon/regularLessonClockIc.svg
  src/assets/icon/regularLessonNotebookIc.svg
  src/assets/icon/regularLessonPencilIc.svg
  src/assets/icon/regularLessonStudentIc.svg
  src/assets/index.ts
  src/components/RegularLesson/Header.tsx
  src/components/RegularLesson/LessonDate.tsx
  src/components/RegularLesson/LessonInformation.tsx
  src/components/RegularLesson/StudentInformation.tsx
  src/pages/RegularLesson.tsx
  src/style/theme.ts
Labels: 희정, feat-UI

#22 Feat#10 on boarding/swiper
  package.json
  src/Router.tsx
  src/assets/icon/FourthSwiperFirstTreeOnBoardingIc.svg
  src/assets/icon/FourthSwiperSecondTreeOnBoardingIc.svg
  src/assets/icon/FourthSwiperThirdTreeOnBoardingIc.svg
  src/assets/icon/MainLogoGradationOnBoardingIc.svg
  src/assets/icon/MainLogoOnBoardingIc.svg
  src/assets/icon/ThirdSwiperFirstTreeOnBoardingIc.svg
  src/assets/icon/ThirdSwiperGradationOnBoardingIc.svg
  src/assets/icon/ThirdSwiperSecondTreeOnBoardingIc.svg
  src/assets/icon/ThirdSwiperThirdTreeOnBoardingIc.svg
  src/assets/icon/TuticeTitleLogoOnBoardingIc.svg
  src/assets/index.ts
  src/components/OnBoarding/FirstSwiper.tsx
  src/components/OnBoarding/FourthSwiper.tsx
  src/components/OnBoarding/SecondSwiper.tsx
  src/components/OnBoarding/SwiperTitleLayout.tsx
  src/components/OnBoarding/ThirdSwiper.tsx
  src/core/OnBoarding.ts
  src/main.tsx
  src/pages/OnBoarding.tsx
  src/style/globalStyle.ts
  yarn.lock
Labels: 성경, feat-UI, feat-function, CodeReview

#30 Feat#23 on boarding/page
  src/Router.tsx
  src/assets/index.ts
  src/components/OnBoarding/FirstSwiper.tsx
  src/pages/OnBoarding.tsx
  yarn.lock
Labels: 성경, fix, feat-UI, CodeReview

#59 Feat#58 manage lesson/attendance list
  src/Router.tsx
  src/assets/icon/nextArrowManageLessonIc.svg
  src/assets/icon/smallAttendanceCheckButtonIc.svg
  src/assets/index.ts
  src/atom/common/isModalOpen.ts
  src/components/common/TreeProgress.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/AttnedanceInform.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/MainLessons.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/manageLesson/TreeLevel.tsx
  src/core/checkAttendance/lessonSchedule.ts
  src/core/common/attendanceStatus.ts
  src/core/manageLesson/getLessonByTeacher.ts
  src/hooks/useGetAllLessons.ts
  src/hooks/useModal.ts
  src/pages/ManageLessonDetail.tsx
  src/pages/ManageLessonMain.tsx
Labels: 지수, feat-UI, feat-function, CodeReview

#57 Feat#55 manage lesson/tree level
  src/Router.tsx
  src/assets/icon/nextArrowManageLessonIc.svg
  src/assets/icon/smallAttendanceCheckButtonIc.svg
  src/assets/index.ts
  src/atom/common/isModalOpen.ts
  src/components/common/TreeProgress.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/AttnedanceInform.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/MainLessons.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/manageLesson/TreeLevel.tsx
  src/components/manageLesson/WelcomeTreeLevel.tsx
  src/core/checkAttendance/lessonSchedule.ts
  src/core/common/attendanceStatus.ts
  src/core/manageLesson/getLessonByTeacher.ts
  src/hooks/useGetAllLessons.ts
  src/hooks/useManageLesson.ts
  src/hooks/useModal.ts
  src/pages/ManageLesson.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/ManageLessonMain.tsx
Labels: 지수, feat-UI, feat-function, CodeReview

#54 Feat#52 manage lesson/divide step
  src/Router.tsx
  src/assets/icon/managingLessonClassIc.svg
  src/assets/icon/managingLessonMoneyIc.svg
  src/assets/icon/nextArrowManageLessonIc.svg
  src/assets/icon/smallAttendanceCheckButtonIc.svg
  src/assets/index.ts
  src/atom/common/isModalOpen.ts
  src/atom/mangeLesson/managingStatus.ts
  src/components/common/StudentNameLabel.tsx
  src/components/common/TeacherFooter.tsx
  src/components/common/TreeProgress.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/AttnedanceInform.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/MainLessons.tsx
  src/components/manageLesson/ManageLessonCategory.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/manageLesson/TreeLevel.tsx
  src/components/manageLesson/WelcomeTreeLevel.tsx
  src/core/checkAttendance/lessonSchedule.ts
  src/core/common/attendanceStatus.ts
  src/core/manageLesson/getLessonByTeacher.ts
  src/core/manageLesson/manageLessonStatus.ts
  src/hooks/useGetAllLessons.ts
  src/hooks/useManageLesson.ts
  src/hooks/useModal.ts
  src/pages/CheckLesson.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/ManageLessonMain.tsx
  src/pages/OnBoarding.tsx
Labels: 지수, feat-UI, feat-function, CodeReview

#70 Feat#41 home/parents
  package.json
  src/assets/icon/NoClassLogoParentsHomeIc.svg
  src/assets/icon/fifthTreeParentsHomeIc.svg
  src/assets/icon/firstTreeParentsHomeIc.svg
  src/assets/icon/fourthTreeParentsHomeIc.svg
  src/assets/icon/rightArrowParentsHomeIc.svg
  src/assets/icon/secondTreeParentsHomeIc.svg
  src/assets/icon/thirdTreeParentsHomeIc.svg
  src/assets/index.ts
  src/components/parentsHome/ClassSchedule.tsx
  src/components/parentsHome/ManageClass.tsx
  src/components/parentsHome/NoClassParentsHome.tsx
  src/components/parentsHome/ParentsHome.tsx
  src/components/parentsHome/TodayClassScedule.tsx
  src/components/parentsHome/TodayClassSwiper.tsx
  src/core/parentsHome/parentsHome.ts
  src/pages/Home.tsx
  src/type/parentsHome/childrenLessonType.ts
  yarn.lock
Labels: 성경, feat-UI, feat-function, CodeReview

#73 Feat#47 login/login view
  src/assets/icon/ViewingLoginIc.svg
  src/assets/icon/canViewingLoginIc.svg
  src/assets/index.ts
  src/components/login/AccountManaging.tsx
  src/components/login/LoginButton.tsx
  src/components/login/LoginHeader.tsx
  src/components/login/LoginInput.tsx
  src/pages/Login.tsx
  src/pages/RegisterLesson.tsx
Labels: 은빈, feat-UI, feat-function, CodeReview

#64 Feat#32 parents/calendar
  src/components/Calendar/Days.tsx
  src/style/theme.ts
Labels: 혜인, refactor, feat-UI, feat-function

#69 Feat#65 change schedule/calendar
  src/Router.tsx
  src/assets/icon/EditPencilIc.svg
  src/assets/icon/removeTrashCanIc.svg
  src/assets/index.ts
  src/components/Calendar/ChangeScheduleDays.tsx
  src/pages/ChangeLessonShcedule.tsx
  src/pages/ChangeSchedule.tsx
Labels: 혜인, feat-UI, feat-function, CodeReview

#72 Feat#68 register lesson/time slider
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
  src/pages/TimePickerPage.tsx
Labels: 희정, feat-UI, feat-function, CodeReview

#63 Feat#56 register lesson/slider
  package.json
  src/Router.tsx
  src/assets/index.ts
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
  src/pages/TimePickerPage.tsx
  yarn.lock
Labels: 희정, feat-UI, feat-function, CodeReview

#66 Feat#50 register lesson/register student and lesson name logic
  src/assets/icon/registerLessonInputIc.svg
  src/assets/index.ts
  src/components/RegisterLessonPage/Footer.tsx
  src/components/RegisterLessonPage/Header.tsx
  src/components/RegisterLessonPage/LessonInput.tsx
  src/pages/RegisterLesson.tsx
  src/style/theme.ts
Labels: 희정, feat-UI, feat-function, CodeReview

#80 Feat#79 manage lesson/register payment
  src/Router.tsx
  src/assets/icon/editPaymentIc.svg
  src/assets/icon/fruitPaymentIc.svg
  src/assets/index.ts
  src/components/manageLesson/StudentPayment.tsx
  src/core/manageLesson/getPaymentRecord.ts
  src/hooks/useGetPaymentRecord.ts
  src/pages/RegisterPayment.tsx
Labels: 지수, feat-UI, feat-function, CodeReview

#77 Refactor#76 manage lesson/lesson
  src/Router.tsx
  src/assets/icon/editPaymentIc.svg
  src/assets/icon/fruitPaymentIc.svg
  src/assets/index.ts
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/StudentPayment.tsx
  src/components/manageLesson/TreeImage.tsx
  src/core/checkAttendance/lessonSchedule.ts
  src/core/manageLesson/getPaymentRecord.ts
  src/core/manageLesson/lessonStatusImage.ts
  src/hooks/useGetPaymentRecord.ts
  src/pages/RegisterPayment.tsx
Labels: 지수, refactor

#75 Feat#62 manage lesson/pay ment UI
  src/Router.tsx
  src/assets/icon/editPaymentIc.svg
  src/assets/icon/fruitPaymentIc.svg
  src/assets/icon/registerPaymentManageLessonIc.svg
  src/assets/icon/sendPaymentAlarmManageLessonIc.svg
  src/assets/index.ts
  src/components/login/LoginHeader.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/ManageLessonCategory.tsx
  src/components/manageLesson/SendPaymentAlarmManageLessonModal.tsx
  src/components/manageLesson/StudentLesson.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/StudentPayment.tsx
  src/components/manageLesson/StudentPayments.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/teacherHome/UpcomingClass.tsx
  src/core/checkAttendance/lessonSchedule.ts
  src/core/manageLesson/getLessonPaymentRecordByTeacher.ts
  src/core/manageLesson/getPaymentRecord.ts
  src/core/manageLesson/lessonStatusImage.ts
  src/core/manageLesson/manageLessonStatus.ts
  src/core/manageLesson/paymentStatusImage.ts
  src/hooks/useGetAllPayments.ts
  src/hooks/useGetPaymentRecord.ts
  src/hooks/useMoveToLessonDetail.ts
  src/pages/ManageLessonDetail.tsx
  src/pages/RegisterPayment.tsx
Labels: 지수, feat-UI, feat-function, CodeReview

#88 Refactor#87 home/refactor data flow
  src/components/teacherHome/AlarmBanner.tsx
  src/components/teacherHome/AlarmNUpcomingClass.tsx
  src/components/teacherHome/NoClassHome.tsx
  src/components/teacherHome/UpcomingClassBoard.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/components/teacherHome/WelcomeTeacher.tsx
  src/hooks/useGetLatestScheduleByTeacher.ts
  src/hooks/useGetTodayScheduleByTeacher.ts
  src/pages/Home.tsx
Labels: 지수, refactor

#101 Refactor#87 home/refactor modal data flow
  src/components/common/AttendanceCheckModal.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/core/teacherHome/teacherHome.ts
Labels: 지수, refactor

#89 Feat#83 login/check box
  src/atom/signup/signup.ts
  src/components/signup/AgreeChecking.tsx
  src/components/signup/PasswordAgreeChecking.tsx
  src/components/signup/RegexField.tsx
  src/components/signup/Role.tsx
  src/components/signup/StepRenderer.tsx
  src/components/signup/UserCheckList.tsx
  src/core/Login/ListData.ts
  src/type/SignUp/newUserDataType.ts
Labels: 은빈, feat-UI, feat-function, code-review

#91 Feat#84 no attendance check/view
  src/Router.tsx
  src/assets/index.ts
  src/components/common/NoCheckPageAttendanceButton.tsx
  src/components/noAttendance/NoAttendanceheader.tsx
  src/components/noAttendance/NoCheckAttendanceContanier.tsx
  src/components/noAttendance/NoCheckLesson.tsx
  src/core/noAttendanceCheck/noAttendance.ts
  src/hooks/useNoAttendance.ts
  src/pages/NoAttendanceCheck.tsx
Labels: 혜인, feat-UI, code-review

#93 Feat#92 manage lesson/view
  src/assets/icon/bellwithAlamIC.svg
  src/assets/index.ts
  src/components/manageLesson/ExtensionQuestion.tsx
  src/core/manageLesson/getMissingMaintenanceLesson.ts
  src/pages/ManageLessonMain.tsx
Labels: 혜인, feat-UI

#97 Feat#96 mypage/view
  src/Router.tsx
  src/components/mypage/Account.tsx
  src/components/mypage/Header.tsx
  src/components/mypage/Terms.tsx
  src/pages/Mypage.tsx
Labels: 혜인, feat-UI

#104 Refactor#103 calendar/refact1
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/Calendar/Change/DayItemchange.tsx
  src/components/Calendar/Change/Days.tsx
  src/components/Calendar/ChangeScheduleDays.tsx
  src/components/Calendar/Dayofweek.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/Parents/ParentDayItem.tsx
  src/components/Calendar/Parents/ParentModal.tsx
  src/components/Calendar/Parents/ParentsDays.tsx
  src/components/Calendar/RegisterLesson/DayItem.tsx
  src/components/Calendar/RegisterLesson/Days.tsx
  src/components/Calendar/RegisterLesson/RegisterModal.tsx
  src/components/Calendar/StickCalendar.tsx
  src/components/Calendar/YearandMonth.tsx
  src/hooks/useGetScheduleChild.ts
  src/hooks/useGetTeacherSchedule.ts
  src/pages/ChangeSchedule.tsx
  src/pages/ParentCalendar.tsx
  src/pages/RegisterCalendar.tsx
  src/type/calendar/calendarLessonsType.ts
  src/type/calendar/dayItemType.ts
  src/type/calendar/daysPropsType.ts
  src/type/calendar/modalType.ts
Labels: 혜인, refactor, code-review

#108 Feat#82 register lesson/date slider data
  src/assets/icon/regularLessonGroupIc.svg
  src/assets/index.ts
  src/atom/common/datePicker.ts
  src/atom/timePicker/timePicker.ts
  src/components/RegisterLessonPage/Footer.tsx
  src/components/RegisterLessonPage/LessonInput.tsx
  src/components/RegularLesson/Footer.tsx
  src/components/RegularLesson/LessonDate.tsx
  src/components/RegularLesson/LessonInformation.tsx
  src/components/RegularLesson/SelectedDayAndTime.tsx
  src/components/RegularLesson/StudentInformation.tsx
  src/components/RegularLesson/TimePicker/DatePicker.tsx
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
  src/core/common/studentColor.ts
  src/pages/RegisterLesson.tsx
  src/pages/RegularLesson.tsx
Labels: 희정, fix, feat-UI, feat-function, code-review

#105 Feat#71 parents lesson record/lessen record
  src/Router.tsx
  src/assets/icon/LessonInfoLessonRecordIc.svg
  src/assets/index.ts
  src/components/lessonRecord/LessonRecordDetail.tsx
  src/components/lessonRecord/PastLessonRecord.tsx
  src/components/lessonRecord/PastLessonRecordList.tsx
  src/components/lessonRecord/RestOfClassesInfo.tsx
  src/core/common/ProgressTree.ts
  src/pages/LessonDetail.tsx
Labels: 성경, feat-UI, code-review

#112 Feat#109 tuition payment/payment view
  src/Router.tsx
  src/assets/icon/tuitionPaymentRadioButtonCheckedIc.svg
  src/assets/icon/tuitionPaymentRadioButtonNotCheckedIc.svg
  src/assets/index.ts
  src/atom/timePicker/timePicker.ts
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/tuitionPayment/Footer.tsx
  src/components/tuitionPayment/Header.tsx
  src/components/tuitionPayment/PaymentInput.tsx
  src/pages/TuitionPayment.tsx
Labels: 희정, feat-UI, feat-function, code-review

#116 Feat#110 parents lesson record/lesson info
  package.json
  src/Router.tsx
  src/assets/icon/copyAccountNumberLessonInfoIc.svg
  src/assets/index.ts
  src/components/lessonRecord/LessonInfoItemLayout.tsx
  src/components/lessonRecord/LessonInfoList.tsx
  src/core/Parents/lessonInfo.ts
  src/pages/LessonInfo.tsx
  yarn.lock
Labels: 성경, feat-UI, feat-function, code-review

#119 Feat#114 signup/welcome signup
  src/assets/icon/bellWelcomeIc.svg
  src/assets/icon/nextArrowWelcomeIc.svg
  src/assets/index.ts
  src/components/login/LoginHeader.tsx
  src/components/signup/StepRenderer.tsx
  src/components/welcomeSignup/AfterSignup.tsx
  src/components/welcomeSignup/AlertSignup.tsx
  src/components/welcomeSignup/ButtonLayout.tsx
  src/components/welcomeSignup/WelcomeSignup.tsx
Labels: 은빈, feat-UI, code-review

#125 Feat#120 lesson share/UI
  index.html
  public/tutice.png
  src/Router.tsx
  src/assets/index.ts
  src/components/lessonShare/KakaoShare.tsx
  src/pages/LessonShare.tsx
  yarn.lock
Labels: 지수, feat-UI, feat-function, code-review

#126 Feat#122 common/responsive web
  src/components/lessonShare/KakaoShare.tsx
  src/pages/LessonShare.tsx
  src/style/globalStyle.ts
Labels: 지수, feat-UI, code-review

#130 Feat#129 manage lesson/payment get api
  src/api/getPaymentRecordView.ts
  src/core/manageLesson/getPaymentRecord.ts
  src/hooks/useGetPaymentRecord.ts
  src/pages/RegisterPayment.tsx
Labels: 지수, feat-function

#136 Feat#118 register lesson/total refactoring
  src/atom/timePicker/timePicker.ts
  src/components/RegularLesson/Footer.tsx
  src/components/RegularLesson/LessonDate.tsx
  src/components/RegularLesson/LessonInformation.tsx
  src/components/RegularLesson/SelectedDayAndTime.tsx
  src/components/RegularLesson/TimePicker/DatePicker.tsx
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
Labels: 희정, feat-UI, feat-function, code-review

#137 Feat#132 signup/view refactor
  src/assets/icon/RoleCheckSignupIc.svg
  src/assets/icon/RoleNoneCheckSignupIc.svg
  src/assets/index.ts
  src/components/signup/AgreeChecking.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PasswordAgreeChecking.tsx
  src/components/signup/Role.tsx
  src/core/signup/signupErrorMessage.ts
Labels: feat-UI

#138 Feat#131 common/prepayment modal
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/Calendar/Parents/ParentDayItem.tsx
  src/components/Calendar/Parents/ParentModal.tsx
  src/components/Calendar/RegisterLesson/DayItem.tsx
  src/components/Calendar/RegisterLesson/RegisterModal.tsx
  src/components/EditSchedule/EditPageLessonInformation.tsx
  src/components/RegularLesson/TimePicker/DatePicker.tsx
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
  src/components/common/AttendanceCheckButton.tsx
  src/components/common/AttendanceStatusButton.tsx
  src/components/common/BasicDoubleModal.tsx
  src/components/common/BasicSingleModal.tsx
  src/components/common/NoCheckPageAttendanceButton.tsx
  src/components/common/RoundBottomMiniButton.tsx
  src/components/common/SnackBarPopup.tsx
  src/components/common/StudentColorBox.tsx
  src/components/common/SubjectLabel.tsx
  src/components/common/TeacherFooter.tsx
  src/components/common/ToastModal.tsx
  src/components/common/TreeProgress.tsx
  src/components/login/LoginButton.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/ExtensionQuestion.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/ManageLessonCategory.tsx
  src/components/modal/PreypaymentModal.tsx
  src/components/signup/AgreeChecking.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/teacherHome/UpcomingClass.tsx
  src/components/teacherHome/UpcomingClassBoard.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/components/teacherHome/banner/NoclassBanner.tsx
  src/components/welcomeSignup/ButtonLayout.tsx
  src/hooks/useGetLessonByUser.ts
  src/pages/Home.tsx
  src/pages/LessonShare.tsx
Labels: 지수, feat-UI, feat-function

#140 Feat#109 tuition payment/payment view
  src/Router.tsx
  src/assets/icon/tuitionPaymentRadioButtonCheckedIc.svg
  src/assets/icon/tuitionPaymentRadioButtonNotCheckedIc.svg
  src/assets/index.ts
  src/atom/registerPayment/registerPayment.ts
  src/atom/timePicker/timePicker.ts
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/registerPayment/PaymentDatePicker.tsx
  src/components/tuitionPayment/Footer.tsx
  src/components/tuitionPayment/Header.tsx
  src/components/tuitionPayment/PaymentInput.tsx
  src/hooks/useGetPaymentRecord.ts
  src/pages/RegisterPayment.tsx
  src/pages/TuitionPayment.tsx
Labels: 희정, feat-function, code-review

#142 Feat#139 missing attendance/get api
  src/api/getLessonByUser.ts
  src/api/getMissingAttendanceSchedule.ts
  src/assets/icon/backButtonSignupIc.svg
  src/components/common/BackButton.tsx
  src/components/common/NoCheckPageAttendanceButton.tsx
  src/components/noAttendance/NoAttendanceheader.tsx
  src/components/noAttendance/NoCheckAttendanceContanier.tsx
  src/components/noAttendance/NoCheckLesson.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/hooks/useGetLessonByUser.ts
  src/hooks/useGetMissingAttendanceSchedule.ts
  src/pages/NoAttendanceCheck.tsx
  src/style/globalStyle.ts
  src/type/common/scheduleType.ts
Labels: 지수, refactor, feat-UI, feat-function

#143 Refactor#141 common/attendacne modal
  src/atom/attendanceCheck/attendanceLesson.ts
  src/components/common/AttendanceCheckModal.tsx
  src/components/common/BackButton.tsx
  src/components/common/ToastModal.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/noAttendance/NoCheckAttendanceContanier.tsx
  src/components/noAttendance/NoCheckLesson.tsx
  src/pages/ManageLessonDetail.tsx
Labels: 지수, refactor

#146 Feat#134 parents calendar/api
  src/api/getScheduleByUser.ts
  src/components/Calendar/Parents/ParentModal.tsx
  src/components/Calendar/Parents/ParentsDays.tsx
  src/hooks/useGetScheduleByUser.ts
  src/pages/ParentCalendar.tsx
  src/type/scheduleType.ts
Labels: 혜인, feat-function, code-review

#157 Feat#151 change schedule/update api
  src/api/getScheduleByUser.ts
  src/api/updateSchedule.ts
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/EditSchedule/EditDatePicker.tsx
  src/components/EditSchedule/EditPageFooter.tsx
  src/components/EditSchedule/EditPageLessonInformation.tsx
  src/hooks/useGetScheduleByUser.ts
Labels: 혜인, feat-function

#158 Feat#90 signup/api
  src/api/localSignUp.ts
  src/api/localSignup.ts
  src/components/signup/PasswordAgreeChecking.tsx
  src/components/signup/Role.tsx
Labels: 은빈, feat-function, code-review

#162 Feat#151 change schedule/update api
  src/components/EditSchedule/EditFooterButton.tsx
  src/components/EditSchedule/EditPageFooter.tsx
  src/components/common/BottomButton.tsx
  src/pages/EditSchedule.tsx
Labels: 혜인, feat-function, code-review

#166 Refactor#153 manage lesson/payment modal
  src/api/getLessonByTeacher.ts
  src/api/getLessonPaymentRecordByTeacher.ts
  src/components/manageLesson/MainLessons.tsx
  src/hooks/useGetAllLessons.ts
  src/type/manageLesson/lessonListType.ts
Labels: 지수, fix

#169 Feat#167 manage lesson/link api
  src/api/getLessonScheduleByTeacher.ts
  src/api/updateScheduleAttendance.ts
  src/components/common/AttendanceDoubleCheckingModal.tsx
  src/components/common/SendAlarmCheckModal.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/manageLesson/WelcomeTreeLevel.tsx
  src/components/modal/ParentsDisabledAlarmModal.tsx
  src/hooks/useGetLessonScheduleByTeacher.ts
  src/hooks/useManageLesson.ts
  src/pages/ManageLessonDetail.tsx
  src/type/manageLesson/scheduleDataType.ts
  src/type/manageLesson/scheduleListType.ts
Labels: 지수, feat-function, code-review

#170 Fix#167 manage lesson/link api
  src/api/getLessonScheduleByTeacher.ts
  src/components/common/SendAlarmCheckModal.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/manageLesson/WelcomeTreeLevel.tsx
  src/hooks/useGetLessonScheduleByTeacher.ts
Labels: 지수, fix

#172 [ feat ] manifest.json 생성
  manifest.json
Labels: 지수, feat-function

#179 Feat#177 parents view/get
  src/api/getLessonByParents.ts
  src/api/getLessonByUser.ts
  src/api/getLessonDetailByParents.ts
  src/api/getTodayScheduleByParents.ts
  src/components/parentsHome/ClassSchedule.tsx
  src/components/parentsHome/ManageClass.tsx
  src/components/parentsHome/TodayClassScedule.tsx
  src/components/parentsHome/TodayClassSwiper.tsx
  src/hooks/useGetLessonByParents.ts
  src/hooks/useGetLessonDetailByParents.ts
  src/hooks/useGetTodayScheduleByParents.ts
  src/pages/Home.tsx
Labels: 혜인, feat-function, code-review

#182 Feat#163 welcome signup/routing
  src/Router.tsx
  src/components/common/BackButton.tsx
  src/components/signup/PasswordAgreeChecking.tsx
  src/components/welcomeSignup/AfterSignup.tsx
  src/components/welcomeSignup/AlertSignup.tsx
  src/components/welcomeSignup/ButtonLayout.tsx
  src/components/welcomeSignup/WelcomeLayout.tsx
  src/pages/WelcomeSignup.tsx
  src/type/manageLesson/scheduleListType 2.ts
Labels: 은빈, feat-UI, feat-function, code-review

#184 Feat#181 parent detail/apiget
  src/Router.tsx
  src/api/getLessonDetailByParents.ts
  src/api/getLessonScheduleByParents.ts
  src/components/EditSchedule/EditDatePicker.tsx
  src/components/EditSchedule/EditFooterButton.tsx
  src/components/EditSchedule/EditPageFooter.tsx
  src/components/lessonRecord/LessonInfoList.tsx
  src/components/lessonRecord/LessonRecordDetail.tsx
  src/components/parentsHome/ClassSchedule.tsx
  src/components/parentsHome/ManageClass.tsx
  src/components/parentsHome/TodayClassScedule.tsx
  src/components/parentsHome/TodayClassSwiper.tsx
  src/hooks/useGetLessonDetailByParents.ts
  src/hooks/useGetLessonScheduleByParents.ts
  src/hooks/useGetTodayScheduleByParents.ts
Labels: 혜인, feat-function

#186 Feat#175 manage lesson/payment api
  src/api/getLessonPaymentRecordByTeacher.ts
  src/api/getPaymentRecordView.ts
  src/api/getScheduleByUser.ts
  src/api/updatePaymentRecord.ts
  src/atom/registerPayment/registerPayment.ts
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/Calendar/Change/DayItemchange.tsx
  src/components/Calendar/Parents/ParentDayItem.tsx
  src/components/Calendar/Parents/ParentModal.tsx
  src/components/Calendar/RegisterLesson/DayItem.tsx
  src/components/Calendar/RegisterLesson/RegisterModal.tsx
  src/components/EditSchedule/EditPageStudentInformation.tsx
  src/components/common/AttendanceCheckModal.tsx
  src/components/common/SendAlarmCheckModal.tsx
  src/components/lessonRecord/LessonRecordDetail.tsx
  src/components/manageLesson/ExtensionLessonContainer.tsx
  src/components/manageLesson/ExtensionQuestion.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/StudentPayment.tsx
  src/components/manageLesson/StudentPayments.tsx
  src/components/noAttendance/NoCheckAttendanceContanier.tsx
  src/components/parentsHome/ManageClass.tsx
  src/components/parentsHome/TodayClassScedule.tsx
  src/components/registerPayment/PaymentDatePicker.tsx
  src/components/teacherHome/UpcomingClass.tsx
  src/hooks/useGetLessonPaymentRecordByTeacher.ts
  src/hooks/useGetPaymentRecordView.ts
  src/pages/CompleteCheckAttendance.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/RegisterPayment.tsx
  src/type/manageLesson/paymentRecordType.ts
  src/type/manageLesson/registerPaymentType.ts
Labels: 지수, feat-function

#190 Feat#183 manage lesson/alarm
  src/api/requestPaymentRecordNotification.ts
  src/components/manageLesson/SendPaymentAlarmManageLessonModal.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/manageLesson/StudentPayment.tsx
  src/components/manageLesson/StudentPayments.tsx
  src/components/teacherHome/UpcomingClass.tsx
  src/pages/Home.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/RegisterPayment.tsx
Labels: 지수, feat-function

#187 Feat#174 manage lesson/api
  src/api/createLessonMaintenance.ts
  src/api/getMissingMaintenanceLesson.ts
  src/components/manageLesson/ExtensionLessonContainer.tsx
  src/components/manageLesson/ExtensionLessonModal.tsx
  src/components/manageLesson/ExtensionQuestion.tsx
  src/hooks/useExtensionLesson.ts
  src/hooks/useGetMissingMaintenanceLesson.ts
  src/pages/Home.tsx
Labels: 희정, feat-function, code-review

#191 Feat#188 home/attendance check
  src/Router.tsx
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/Calendar/Change/Days.tsx
  src/components/common/AttendanceCheckButton.tsx
  src/components/common/AttendanceCheckModal.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/teacherHome/WelcomeNUpPreviewBanner.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/hooks/useGetTodayScheduleByTeacher.ts
  src/pages/ChangeSchedule.tsx
  src/pages/Home.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/Mypage.tsx
Labels: 지수, feat-function

#198 Feat#189 regular lesson/postapi
  src/api/getTemporarySchedule.ts
  src/atom/timePicker/timePicker.ts
  src/components/RegularLesson/LessonDate.tsx
Labels: 희정, feat-function, code-review

#202 Fix#197 attendance/modal fix
  src/components/common/SendAlarmCheckModal.tsx
  src/components/manageLesson/SendPaymentAlarmManageLessonModal.tsx
  src/components/manageLesson/StudentLesson.tsx
  src/components/manageLesson/StudentPayments.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/hooks/useGetLessonDetailByParents.ts
  src/hooks/useGetTodayScheduleByParents.ts
  src/hooks/useTeacherFooter.ts
  src/pages/CompleteCheckAttendance.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/RegisterPayment.tsx
Labels: 지수, fix, code-review

#199 [ parentsLessonRecord ] 입금내역 뷰 API 연결
  src/api/getDepositRecord.ts
  src/components/lessonRecord/DepositRecord.tsx
  src/components/lessonRecord/DepositRecordItem.tsx
  src/hooks/useGetDepositRecord.ts
  src/type/lessonRecord/lessonRecord.ts
Labels: 성경, feat-function, code-review

#206 Feat#203 common/class tree button
  src/components/common/CreateTreeCode.tsx
  src/components/teacherHome/NoClassHome.tsx
  src/components/teacherHome/YesClassHome.tsx
  src/pages/ManageLessonMain.tsx
Labels: 지수, feat-UI, feat-function

#210 Feat#207 qa/test
  index.html
  src/components/common/AttendanceDoubleCheckingModal.tsx
  src/components/lessonRecord/DepositRecordItem.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/modal/FutureImpossibleModal.tsx
  src/components/teacherHome/AlarmBanner.tsx
  src/hooks/useGetLessonDetailByParents.ts
Labels: 지수, fix

#211 Refactor#205 register lesson/refactor
  src/api/createLesson.ts
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/RegisterLessonPage/Header.tsx
  src/components/RegularLesson/Footer.tsx
  src/components/RegularLesson/Header.tsx
  src/components/RegularLesson/SelectedDayAndTime.tsx
  src/components/RegularLesson/TimePicker/DatePicker.tsx
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
  src/components/tuitionPayment/Footer.tsx
  src/components/tuitionPayment/Header.tsx
  src/components/tuitionPayment/PaymentInput.tsx
Labels: 희정, refactor, fix, feat-function, code-review

#212 Feat#192 signup/cookie
  package.json
  src/api/cookie.ts
  src/api/localSignUp.ts
  src/atom/loginUser/loginUser.ts
  src/components/login/LoginInput.tsx
  src/components/signup/PasswordAgreeChecking.tsx
  src/main.tsx
  yarn.lock
Labels: 은빈, feat-function, code-review

#216 Feat#214 qa/test
  src/components/manageLesson/SendPaymentAlarmManageLessonModal.tsx
  src/style/globalStyle.ts
Labels: 지수, fix

#215 Feat#208 register lesson/invite parents
  src/Router.tsx
  src/api/patchLessonParents.ts
  src/atom/registerLesson/registerLesson.ts
  src/components/RegularLesson/ConnectParentsAndTeacher.tsx
  src/components/login/LoginInput.tsx
Labels: 성경, feat-function, code-review

#218 Refactor#193 signup/view refactor
  src/components/login/AccountManaging.tsx
  src/components/login/LoginInput.tsx
  src/components/signup/AgreeChecking.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/Role.tsx
  src/components/welcomeSignup/AfterSignup.tsx
Labels: 은빈, refactor, feat-UI, code-review

#219 Feat#217 common/private router
  src/Router.tsx
  src/api/createLesson.ts
  src/api/createLessonMaintenance.ts
  src/api/getDepositRecord.ts
  src/api/getLatestScheduleByTeacher.ts
  src/api/getLessonByParents.ts
  src/api/getLessonByTeacher.ts
  src/api/getLessonByUser.ts
  src/api/getLessonDetailByParents.ts
  src/api/getLessonPaymentRecordByTeacher.ts
  src/api/getLessonScheduleByParents.ts
  src/api/getLessonScheduleByTeacher.ts
  src/api/getMissingAttendanceSchedule.ts
  src/api/getMissingMaintenanceLesson.ts
  src/api/getPastLessonRecord.ts
  src/api/getPaymentRecordView.ts
  src/api/getScheduleByUser.ts
  src/api/getTemporarySchedule.ts
  src/api/getTodayScheduleByParents.ts
  src/api/getTodayScheduleByTeacher.ts
  src/api/patchDeviceToken.ts
  src/api/patchLessonParents.ts
  src/api/requestAttendanceNotification.ts
  src/api/requestPaymentRecordNotification.ts
  src/api/updatePaymentRecord.ts
  src/api/updateSchedule.ts
  src/api/updateScheduleAttendance.ts
  src/components/RegisterLessonPage/LessonInput.tsx
  src/components/login/LoginInput.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PasswordAgreeChecking.tsx
  src/components/tuitionPayment/PaymentInput.tsx
  src/components/welcomeSignup/AlertSignup.tsx
  src/utils/common/isLogined.ts
  src/utils/common/privateRoute.tsx
Labels: 지수, fix, feat-function

#221 [ feat ] 초대코드 링크 생성
  src/main.tsx
  src/pages/LessonShare.tsx
Labels: 지수, feat-function

#225 [ feat ] userRole 따라 다른 홈페이지 보여지도록구현
  src/pages/Home.tsx
Labels: 지수, feat-function

#227 Refactor#213 regular lesson/slider
  src/components/RegularLesson/LessonInformation.tsx
  src/components/RegularLesson/TimePicker/DatePicker.tsx
Labels: 희정, refactor, feat-function

#226 Refactor#163 login/refactor view
  src/atom/loginUser/loginUser.ts
  src/components/common/BackButton.tsx
  src/components/login/LoginInput.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PasswordAgreeChecking.tsx
Labels: 은빈, feat-UI, code-review

#231 Fix#229 signup/cookie
  src/components/signup/AgreeChecking.tsx
  src/components/signup/PasswordAgreeChecking.tsx
Labels: 은빈, refactor, feat-function, code-review

#233 Refactor#224 edit schedule/page layout
  src/components/EditSchedule/EditPageFooter.tsx
  src/components/EditSchedule/EditPageLessonInformation.tsx
  src/components/EditSchedule/EditPageTime.tsx
Labels: 혜인, refactor, feat-UI

#237 [ fix ] 새로고침하면 recoil 날아가는 오류 수정
  src/atom/EditSchedule/editDateState.ts
Labels: 혜인, fix

#238 Feat#230 qa/test
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/Calendar/RegisterLesson/Days.tsx
  src/components/Calendar/RegisterLesson/RegisterModal.tsx
  src/components/modal/PreypaymentModal.tsx
  src/components/tuitionPayment/Footer.tsx
  src/pages/LessonShare.tsx
  src/type/calendar/dayItemType.ts
Labels: 지수, fix, feat-function

#239 Refactor#234 edit lesson schedule/refactoring
  src/components/EditSchedule/EditDatePicker.tsx
  src/components/EditSchedule/EditPageFooter.tsx
  src/components/EditSchedule/EditTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
Labels: fix, feat-function, code-review

#245 Feat#242 common/router fix
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/mypage/Account.tsx
  src/components/signup/AgreeChecking.tsx
  src/utils/common/privateRoute.tsx
Labels: 지수, fix

#250 Hotfix#249 welcome/ux edit
  src/components/login/LoginInput.tsx
  src/components/welcomeSignup/AfterSignup.tsx
Labels: 은빈, feat-UI

#251 [ fix ] flex로 오타 수정
  src/components/Calendar/Change/ChangeModal.tsx
Labels: fix

#252 [ hotfix ] apidusruf pastLessonRecord 연결 추가
  src/components/lessonRecord/PastLessonRecord.tsx
  src/components/lessonRecord/PastLessonRecordList.tsx
  src/hooks/useGetPastLessonRecord.ts
  src/type/lessonRecord/lessonRecord.ts
Labels: 혜인, fix

#253 [ hotfix ] 오타수정
  src/components/lessonRecord/PastLessonRecord.tsx
Labels: 혜인, fix

#255 [ feat ] 알림 로직 수정
  src/components/welcomeSignup/AlertSignup.tsx
Labels: 지수, fix

#257 [ feat ] 학부모 푸터 구현
  src/Router.tsx
  src/assets/icon/MypageSelectedParentsHomeIc.svg
  src/assets/icon/calendarSelectedParentsHomeIc.svg
  src/assets/icon/calendarUnselectedparentsHomeIc.svg
  src/assets/icon/homeSelectedParentsHomeIc.svg
  src/assets/icon/homeUnselectedParentsHomeIc.svg
  src/assets/icon/myPageUnselectedParentsHomeIc.svg
  src/assets/index.ts
  src/atom/common/parentsFooterCategory.ts
  src/components/common/ParentsFooter.tsx
  src/components/common/ParentsFooterIcons.tsx
  src/components/common/TeacherFooter.tsx
  src/components/parentsHome/ParentsHome.tsx
  src/core/parentsHome/parentsFooter.ts
  src/hooks/useParentsFooter.ts
  src/pages/ParentCalendar.tsx
  src/type/parentsHome/ParentsFooterType.ts
Labels: 성경, feat-UI, feat-function, code-review

#260 Fix#244 regular lesson/slider
  src/pages/LessonShare.tsx
Labels: 희정, fix, feat-function, code-review
