Repository Gwasuwon-shot/Tutice_Client, pull requests merged in 2023-09, with the labels that each got.

#275 Refactor#236 signup/refactoring
  index.html
  src/components/login/LoginHeader.tsx
  src/components/login/LoginInput.tsx
  src/components/signup/AgreeChecking.tsx
  src/components/signup/InputLayout.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PasswordAgreeChecking.tsx
  src/components/signup/StepRenderer.tsx
  src/hooks/useSignupFormState.ts
Labels: refactor, code-review

#278 Refactor#270 calendar
  src/components/Calendar/Change/DayItemchange.tsx
  src/components/Calendar/Change/Days.tsx
  src/components/Calendar/Parents/ParentDayItem.tsx
  src/components/Calendar/Parents/ParentsDays.tsx
  src/components/Calendar/RegisterLesson/DayItem.tsx
  src/components/Calendar/RegisterLesson/Days.tsx
  src/type/calendar/daysPropType.ts
Labels: 혜인, refactor

#283 Qa#281 2nd
  src/components/welcomeSignup/ButtonLayout.tsx
  src/pages/OnBoarding.tsx
Labels: 성경, QA

#289 Refactor#277 signup/3rd qa
  src/components/common/BottomButton.tsx
Labels: refactor, code-review, QA

#291 Qa#282 1st
  src/atom/timePicker/timePicker.ts
  src/components/RegisterLessonPage/Footer.tsx
  src/components/RegisterLessonPage/Header.tsx
  src/components/RegisterLessonPage/LessonInput.tsx
  src/components/RegularLesson/Footer.tsx
  src/components/RegularLesson/Header.tsx
  src/components/RegularLesson/LessonDate.tsx
  src/components/RegularLesson/LessonInformation.tsx
  src/components/RegularLesson/SelectedDayAndTime.tsx
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
  src/components/RegularLesson/TimePicker/TimePicker.tsx
  src/components/registerPayment/PaymentDatePicker.tsx
  src/components/tuitionPayment/Footer.tsx
  src/components/tuitionPayment/Header.tsx
  src/components/tuitionPayment/PaymentInput.tsx
  src/pages/RegisterLesson.tsx
  src/pages/RegularLesson.tsx
Labels: 희정, QA

#294 Hotfix/#292 signup/hotfix merging
  src/components/signup/AgreeChecking.tsx
  src/hooks/signupLogin/useAgreementStates.ts
  src/type/parentsHome/ParentsFooterType 2.ts
Labels: refactor

#295 [ fix ] 빌드에러 수정
  src/components/signup/AgreeChecking.tsx
  src/hooks/signupLogin/useAgreementStates.ts
Labels: fix

#301 Fix#299 qa/lesson
  src/api/createLesson.ts
  src/api/getLessonProgress.ts
  src/atom/tuitionPayment/tuitionPayment.ts
  src/components/manageLesson/ExtensionLessonContainer.tsx
  src/components/modal/PreypaymentModal.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/teacherHome/banner/ClassPreviewBanner.tsx
  src/components/tuitionPayment/Footer.tsx
  src/pages/RegisterPayment.tsx
  src/style/globalStyle.ts
Labels: 지수, fix, QA

#296 Qa#284 3rd
  src/components/OnBoarding/FourthSwiper.tsx
  src/components/welcomeSignup/AlertSignup.tsx
  src/components/welcomeSignup/WelcomeLayout.tsx
  src/core/OnBoarding.ts
  yarn.lock
Labels: QA

#300 [ fix ] 도르레 깨짐 오류 수정
  src/components/registerPayment/PaymentDatePicker.tsx
Labels: 희정, fix

#305 Feat#304 qa/routing
  src/components/OnBoarding/ThirdSwiper.tsx
  src/components/common/SendAlarmCheckModal.tsx
  src/components/lessonShare/KakaoShare.tsx
  src/components/modal/FutureImpossibleModal.tsx
  src/components/noAttendance/NoCheckLesson.tsx
  src/components/welcomeSignup/AfterSignup.tsx
  src/components/welcomeSignup/AlertSignup.tsx
  src/components/welcomeSignup/ButtonLayout.tsx
  src/components/welcomeSignup/WelcomeLayout.tsx
  src/pages/CompleteCheckAttendance.tsx
  src/pages/LessonShare.tsx
  src/pages/RegisterLesson.tsx
  src/style/globalStyle.ts
Labels: 지수, fix

#308 Fix#307 regular lesson/button fix
  src/components/RegularLesson/LessonDate.tsx
  src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
Labels: 희정, fix, QA

#315 Qa#311 self2nd
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/Calendar/Change/DayItemchange.tsx
  src/components/Calendar/Parents/ParentDayItem.tsx
  src/components/Calendar/Parents/ParentModal.tsx
  src/components/Calendar/RegisterLesson/DayItem.tsx
Labels: 혜인, QA

#316 Qa#311 self2nd
  src/atom/EditSchedule/editLessonIdx.ts
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/Calendar/Change/DayItemchange.tsx
  src/components/Calendar/Parents/ParentDayItem.tsx
  src/components/Calendar/Parents/ParentModal.tsx
  src/components/Calendar/RegisterLesson/DayItem.tsx
  src/components/EditSchedule/EditPageStudentInformation.tsx
  src/type/editSchedule/editScheduleType.ts
Labels: 혜인, QA

#318 [ feat ] errorMessage Alert 추가
  src/components/signup/AgreeChecking.tsx
Labels: feat-function

#324 Fix#323 sign up/term2 qa
  src/api/postCheckEmail.ts
  src/components/signup/AgreeChecking.tsx
  src/components/signup/EmailCheckButton.tsx
  src/components/signup/EmailDuplicatedModal.tsx
  src/components/signup/NameEmail.tsx
  src/hooks/useSignupFormState.ts
  src/pages/Signup.tsx
  src/type/SignUp/checkDuplicatedEmailType.ts
Labels: 은빈, code-review, QA

#326 Feat#319 signup/UI update
  src/assets/icon/RoleCheckSignupIc.svg
  src/assets/icon/RoleNoneCheckSignupIc.svg
  src/components/common/index.ts
  src/components/signup/AgreeChecking.tsx
  src/components/signup/AgreeCheckingFrame.tsx
  src/components/signup/NameEmail.tsx
  src/components/signup/PasswordFrame.tsx
  src/components/signup/Role.tsx
  src/components/signup/SignupTitleLayout.tsx
  src/components/signup/StepRenderer.tsx
  src/components/welcomeSignup/AfterSignup.tsx
  src/components/welcomeSignup/AlertSignup.tsx
  src/core/signup/buttonText.ts
  src/core/signup/signupTitle.ts
Labels: 은빈, refactor, code-review
