Repository Gwasuwon-shot/Tutice_Client, pull requests merged in 2023-10, with the labels that each got.

#343 Feat#340 common/design
  src/components/common/AttendanceDoubleCheckingModal.tsx
  src/components/common/NoCheckPageAttendanceButton.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/AttendanceInforms.tsx
Labels: 지수, feat-UI

#345 Feat#344 common/design
  src/components/common/AttendanceDoubleCheckingModal.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/pages/CompleteCheckAttendance.tsx
  src/pages/Login.tsx
  src/pages/ManageLessonDetail.tsx
Labels: 지수, QA

#348 Feat#346 common/ebs
  package.json
  src/App.tsx
  src/Router.tsx
  src/assets/icon/alarmDeniedIc.svg
  src/assets/icon/alarmGrantedIc.svg
  src/assets/icon/ic_exclamation-mark.svg
  src/assets/icon/loadingIc.svg
  src/assets/index.ts
  src/components/common/SendAlarmCheckModal.tsx
  src/components/manageLesson/SendPaymentAlarmManageLessonModal.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/components/mypage/Alarm.tsx
  src/components/parentsHome/ParentsHome.tsx
  src/core/common/loading.json
  src/hooks/useGetLessonDetail.ts
  src/main.tsx
  src/pages/Error.tsx
  src/pages/LessonShare.tsx
  src/pages/Loading.tsx
  src/pages/Mypage.tsx
  yarn.lock
Labels: 지수, QA

#349 Feat#347 landing/update design
  src/assets/icon/AppleOnBoardingIc.svg
  src/assets/icon/logoOnboardingIc.svg
  src/assets/index.ts
  src/components/OnBoarding/FirstSwiper.tsx
  src/components/OnBoarding/FourthSwiper.tsx
  src/components/OnBoarding/ThirdSwiper.tsx
  src/components/welcomeSignup/WelcomeLayout.tsx
  src/pages/OnBoarding.tsx
Labels: 성경, feat-UI

#355 Fix#354 welcome/error fix
  src/Router.tsx
  src/components/signup/AgreeCheckingFrame.tsx
  src/components/welcomeSignup/AfterSignup.tsx
  src/components/welcomeSignup/AllowAlert.tsx
  src/components/welcomeSignup/ButtonLayout.tsx
  src/components/welcomeSignup/WelcomeLayout.tsx
Labels: fix, feat-UI

#342 Qa#327 2nd
  src/components/RegisterLessonPage/Footer.tsx
  src/components/RegisterLessonPage/LessonInput.tsx
  src/components/RegularLesson/LessonDate.tsx
  src/components/RegularLesson/TimePicker/DatePicker.tsx
  src/components/tuitionPayment/PaymentInput.tsx
Labels: 희정, refactor, QA

#365 Fix#358 attendance/qa
  src/Router.tsx
  src/atom/common/agreeSend.ts
  src/components/common/AttendanceCheckModal.tsx
  src/components/common/CreateTreeCode.tsx
  src/components/common/ParentsFooter.tsx
  src/components/common/ParentsFooterIcons.tsx
  src/components/common/SendAlarmCheckModal.tsx
  src/components/common/SnackBarPopup.tsx
  src/components/lessonRecord/DepositRecord.tsx
  src/components/lessonRecord/DepositRecordItem.tsx
  src/components/lessonRecord/NoDeposit.tsx
  src/components/lessonRecord/RestOfClassesInfo.tsx
  src/components/lessonShare/KakaoShare.tsx
  src/components/manageLesson/AttendanceInform.tsx
  src/components/manageLesson/AttendanceInforms.tsx
  src/components/manageLesson/StudentLesson.tsx
  src/components/manageLesson/StudentPayment.tsx
  src/components/manageLesson/StudentPayments.tsx
  src/components/manageLesson/TreeImage.tsx
  src/components/mypage/Account.tsx
  src/components/mypage/Terms.tsx
  src/components/parentsHome/ClassSchedule.tsx
  src/components/parentsHome/ManageClass.tsx
  src/components/parentsHome/NoClassParentsHome.tsx
  src/components/teacherHome/NoClassHome.tsx
  src/components/teacherHome/TeacherHome.tsx
  src/components/welcomeSignup/AfterSignup.tsx
  src/hooks/useParentsFooter.ts
  src/pages/CompleteCheckAttendance.tsx
  src/pages/LessonShare.tsx
  src/pages/ManageLessonDetail.tsx
  src/pages/Mypage.tsx
  src/pages/RegisterPayment.tsx
Labels: 지수, QA

#370 Feat#369 login/logout
  src/api/patchLogout.ts
  src/components/mypage/LogoutModal.tsx
Labels: feat-function

#374 Feat#371 lesson info/UI
  src/Router.tsx
  src/api/getLessonRegularSchedule.ts
  src/assets/icon/LessonInfoLessonRecordIc.svg
  src/components/lessonRecord/LessonInfoList.tsx
  src/components/lessonRecord/LessonRecordDetail.tsx
  src/components/manageLesson/StudentNameBox.tsx
  src/hooks/useGetLessonRegularSchedule.ts
  src/pages/LessonInfo.tsx
Labels: 지수, feat-UI, feat-function

#375 Qa#372 register lesson
  src/components/RegularLesson/Header.tsx
  src/components/regularLessonDate/Footer.tsx
Labels: 희정, fix, QA

#377 Fix#376 common/qa
  src/App.tsx
  src/Router.tsx
  src/api/cookie.ts
  src/api/getLessonRegularSchedule.ts
  src/components/manageLesson/MainLesson.tsx
  src/components/modal/CreateImpossibleModal.tsx
  src/components/tuitionPayment/Footer.tsx
  src/hooks/useGetLessonRegularSchedule.ts
  src/pages/ErrorPage.tsx
Labels: 지수, fix, QA

#380 Feat#379 common/writing
  src/assets/icon/addLessonButtonIc.svg
  src/assets/icon/missingMaintenanceTeacherHomeIc.svg
  src/assets/index.ts
  src/components/common/CreateTreeCode.tsx
  src/components/parentsHome/NoClassParentsHome.tsx
  src/components/teacherHome/NoClassHome.tsx
Labels: 지수, QA

#351 Qa#322 calendar
  src/Router.tsx
  src/api/deleteLesson.ts
  src/api/getAttendanceExist.ts
  src/assets/icon/exclamationMarkIc.svg
  src/assets/index.ts
  src/components/Calendar/Change/CannotEditModal.tsx
  src/components/Calendar/Change/ChangeModal.tsx
  src/components/Calendar/Change/EditScheduleButton.tsx
  src/components/EditSchedule/EditPageTime.tsx
  src/components/manageLesson/MainLesson.tsx
  src/components/manageLesson/MainLessons.tsx
  src/components/manageLesson/ManageStudentColorBox.tsx
  src/hooks/useGetAttendanceExist.ts
  src/pages/ManageLessonMain.tsx
  src/pages/MissingMaintenanceLesson.tsx
Labels: QA

#391 [ fix ] 워딩 변경
  src/assets/icon/addTreeCodeButtonManageIc.svg
Labels: 지수, QA
